# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/fileService.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/fileService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/fileService.proto\x12\x0b\x66ileservice\"<\n\x08\x46ileData\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"\'\n\x03\x61\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1c\n\x08UserInfo\x12\x10\n\x08username\x18\x01 \x01(\t\".\n\x08\x46ileInfo\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"%\n\x10\x46ileListResponse\x12\x11\n\tFilenames\x18\x01 \x01(\t\"<\n\x0b\x43lusterInfo\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\x12\x13\n\x0b\x63lusterName\x18\x03 \x01(\t\"G\n\x0c\x43lusterStats\x12\x11\n\tcpu_usage\x18\x01 \x01(\t\x12\x12\n\ndisk_space\x18\x02 \x01(\t\x12\x10\n\x08used_mem\x18\x03 \x01(\t\"\x07\n\x05\x45mpty2\xaa\x04\n\x0b\x46ileservice\x12\x37\n\nUploadFile\x12\x15.fileservice.FileData\x1a\x10.fileservice.ack(\x01\x12>\n\x0c\x44ownloadFile\x12\x15.fileservice.FileInfo\x1a\x15.fileservice.FileData0\x01\x12\x35\n\nFileSearch\x12\x15.fileservice.FileInfo\x1a\x10.fileservice.ack\x12:\n\rReplicateFile\x12\x15.fileservice.FileData\x1a\x10.fileservice.ack(\x01\x12@\n\x08\x46ileList\x12\x15.fileservice.UserInfo\x1a\x1d.fileservice.FileListResponse\x12\x35\n\nFileDelete\x12\x15.fileservice.FileInfo\x1a\x10.fileservice.ack\x12\x37\n\nUpdateFile\x12\x15.fileservice.FileData\x1a\x10.fileservice.ack(\x01\x12@\n\x0fgetClusterStats\x12\x12.fileservice.Empty\x1a\x19.fileservice.ClusterStats\x12;\n\rgetLeaderInfo\x12\x18.fileservice.ClusterInfo\x1a\x10.fileservice.ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.fileService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEDATA']._serialized_start=40
  _globals['_FILEDATA']._serialized_end=100
  _globals['_ACK']._serialized_start=102
  _globals['_ACK']._serialized_end=141
  _globals['_USERINFO']._serialized_start=143
  _globals['_USERINFO']._serialized_end=171
  _globals['_FILEINFO']._serialized_start=173
  _globals['_FILEINFO']._serialized_end=219
  _globals['_FILELISTRESPONSE']._serialized_start=221
  _globals['_FILELISTRESPONSE']._serialized_end=258
  _globals['_CLUSTERINFO']._serialized_start=260
  _globals['_CLUSTERINFO']._serialized_end=320
  _globals['_CLUSTERSTATS']._serialized_start=322
  _globals['_CLUSTERSTATS']._serialized_end=393
  _globals['_EMPTY']._serialized_start=395
  _globals['_EMPTY']._serialized_end=402
  _globals['_FILESERVICE']._serialized_start=405
  _globals['_FILESERVICE']._serialized_end=959
# @@protoc_insertion_point(module_scope)
